wpovernight/woocommerce-pdf-invoices-packing-slips

js/script.js

Without this condition plugin is trying to generate pdf, but one parameter is missing (order_ids), because no one order is selected. Plugin is throwing exception but alert like this should be more understandable.

Check if there are selected orders

---

includes/class-wcpdf-main.php

Continue from #34 
Here's what I want to do:
* I have sales user role that has permission to view order, generate pdf on frontend
* The salesman user_id has added in order meta, and it's not ```customer_id``` meta
If i use filter ```wpo_wcpdf_check_privs``` it still remain obstructed by [class-wcpdf-main.php, line 174](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/includes/class-wcpdf-main.php#L174)
So this is my solution, and maybe better usability filter ```wpo_wcpdf_check_privs``` for others.

better use filter wpo_wcpdf_check_privs

---

includes/documents/abstract-wcpdf-order-document.php

when passing type int to __construct $order_id variable is undefined

FIX Order_Document::__construct undefined variable

---

includes/documents/class-wcpdf-invoice.php

Hi! 👋🏼
Simple PR to fix the notice below.
```
PHP Notice:  Undefined variable: config_link in /wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/class-wcpdf-invoice.php on line 365
```

Fix notice when using invoice number by plugin

---

includes/class-wcpdf-main.php

registers custom webhook topics for all PDF documents, in the format `order.{$document_type}-saved`, so for invoices that would be `order.invoice-saved` and for packing slips `order.packing-slip-saved` etc.

register order webhook topic "saved" for all documents

---

includes/class-wcpdf-admin.php

using `wpo_wcpdf_action_button_class`  the appearance of the button can now be controlled more easily. Here's an example implementation showing a grey checkmark for created documents and a green checkmark for printed ones:
```php
add_action( 'wpo_wcpdf_before_document', function( $document_type, $order ) {
$order->update_meta_data( "wpo_wcpdf_{$document_type}_last_printed", date_i18n( 'Y-m-d H:i:s' ) );
$order->save_meta_data();
}, 10, 2 );
add_filter( 'wpo_wcpdf_action_button_class', function( $class, $document ) {
if ( $order = $document->order ) {
$document_type = $document->get_type();
$printed = $order->get_meta( "wpo_wcpdf_{$document_type}_last_printed" );
if ( !empty( $printed ) ) {
$class .= " printed";
}
}
return $class;
}, 10, 2 );
add_action('admin_enqueue_scripts', function(){ …
```

allow filtering button classes using 

---

includes/class-wcpdf-admin.php
includes/documents/class-wcpdf-invoice.php

Also after setting the date to the future, if clicking "Set invoice number and date" the date showed was current, now fixed!
Also initiates the Invoice number if the date is set in the form data and the number is not.
closes #165

Invoice date set before generating document not being respected

---

includes/class-wcpdf-admin.php
includes/documents/abstract-wcpdf-order-document-methods.php

closes #136
- Fixes duplicate slashes pointed in the issue #136 
- Allows special characters '"!#$%&/()=
- Respects line breaks (clicking enter)
- Respects line breaks with `<br>`
```
eieieieieiei
apapapapapa
<br><br>
eieieieieiei
```
```
eieieieieiei<br />
<br />
apapapapapa<br />
<br />
eieieieieiei
```
```
eieieieieiei
apapapapapa
<br><br>
eieieieieiei
```
```
eieieieieiei
apapapapapa
<br><br>
eieieieieiei
```
```
eieieieieiei<br />
<br />
apapapapapa<br />
<br />
eieieieieiei
```

Fix invoice notes

---

vendor/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php

When the font folder in the temporary wcpdf folder is cleared (but not deleted) or when the font cache files (`.ufm.php`  and `.afm.php`) are deleted for whatever reason (most likely as a result of a false positive in a virus scan), the fonts can no longer be properly loaded and texts appear stacked.
dompdf actually provides a built-in fallback to 'distributed' (bundled) fonts if fonts cannot be loaded from the fonts path, but our version was missing a slash (`DIRECTORY_SEPARATOR`) in the path, so that this fallback would work either.
This PR fixes both the fallback and also adds the extra fonts we bundle by default to it

fix missing directory separator in distributed fonts path

---

templates/Simple/style.css

With this small addition, this issue seems to be solved:
Closes: #196

Fix issue with long URLs in the notes area

---

includes/class-wcpdf-assets.php
includes/class-wcpdf-documents.php
includes/class-wcpdf-install.php
includes/class-wcpdf-settings-general.php
includes/class-wcpdf-settings.php
includes/documents/abstract-wcpdf-order-document.php
woocommerce-pdf-invoices-packingslips.php

This PR introduces a new method of storing the selected template in the database - instead of a relative path (e.g. `wp-content/plugins/woocommerce-pdf-invoices-packing-slips/templates/Simple`, it stores an "id" (e.g. `default/Simple`). When the template path is requested, this id is then matched with a list of paths that is maintained separately.
The "id" is in the form of `{$group}/{$template_name}`, where `group` is the array key that was used when registering the template base path (the folder that holds the actual template subfolders).
This should improve portability by solving a number of edge-case issues:
- Templates are stored outside of the `WP_CONTENT_DIR` (or `ABSPATH`) and conversion from relative path to absolute path fails
- Templates are symlinks (in certain setups using …

Template path portability

---

includes/class-wcpdf-install.php
includes/class-wcpdf-main.php

This replaces `require` with `include` in the `copy_fonts()` method, and logs an error when it fails (instead of crashing with an uncatchable error). Some WPCS has been applied too.
Additionally, all 3 Install procedures are now wrapped in `try ... catch` to avoid other fatal errors from breaking the site.
To test you could throw an error anywhere in the related code:
```php
throw new \Exception( "Error Processing Request", 1 );
```
and to test a failing `include`, the following line could be modified (adding a non-existing suffix, etc):
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/5f728df5b594de10dcd13dd35e534c08285e4688/includes/class-wcpdf-main.php#L712
closes #245

Fail more gracefully during install/upgrade/downgrade

---

includes/class-wcpdf-main.php
includes/documents/abstract-wcpdf-order-document.php
includes/wcpdf-functions.php

closes #151 
This PR adds filters to replace the currency symbols that require RTL text direction support with their ISO currency code equivalents, **only** when the bundled dompdf library is used. We can't make assumptions about external libraries supporting RTL text, so we don't make the replacements when the PDF maker is overriden.
This means that people using our [mpdf extension](https://github.com/wpovernight/woocommerce-pdf-ips-mpdf) should see the actual currency symbol, not the ISO code!
I've also implemented two filters (`wpo_wcpdf_pdf_filters` & `wpo_wcpdf_html_filters`) that allow registering filters that should only be enabled during PDF (or HTML) creation, removing them automatically afterwards. This is used here so that these currency overrides don't apply to regular …

Use ISO currency code for RTL currencies when dompdf is used

---

includes/documents/class-wcpdf-bulk-document.php

closes #263 
- Adds the `wpo_wcpdf_pdf_filters` filter (which was added [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/255)) to the bulk document. 
- Also fixes the currency symbol not displaying in bulk documents as mentioned in this [ticket](https://wordpress.org/support/topic/currency-symbol-error-in-bulk-invoices/).

Add wpo_wcpdf_pdf_filters and currency symbol fix to bulk document

---

includes/documents/abstract-wcpdf-order-document.php

closes #327 
Since 2.13.0 we only store historical settings in the order meta, but this means that non-historical document settings can no longer be read from the order once the settings have been stored.
This PR recombines all non-historical settings with the order settings.

Recombine non-historical settings with order settings

---

includes/class-wcpdf-install.php

closes #331 
Because `get_sequential_number_store()` creates the number store table on the class instantiation, we need to check before that is the table exists. The **Packing Slip number** is only available in **Pro**, so I use that extension main function to create a condition for non `invoice` document number stores.
* Delete existing number stores
* Checkout this commit 96638af7419901e7f26c3edb679b39ac6dc7f4bd
* Generate number stores
* Checkout this branch
* DB migration
Logs:
`2022-02-22T17:22:37+00:00 INFO Default value changed for 'date' column to '1000-01-01 00:00:00' on database table: wp_wcpdf_invoice_number`

Checks if number store table exists before applying DB migration

---

includes/class-wcpdf-setup-wizard.php

closes #299 
stripped slashes from the wizard settings before saving to the database. the slashes that were printed on the frontend and the PDFs don't get printed after this

stripped slashes in wizard settings before saving to db

---

includes/class-wcpdf-settings-general.php
includes/class-wcpdf-settings.php

closes #378
When "General settings" are called the `WC()->template_path()` is not callable, which ends to the hard coded `woocommerce/` default. Applying the WooCommerce filter here catches potential custom filtered paths.

378 fixes bug filtered template path

---

includes/documents/abstract-wcpdf-order-document-methods.php

Fixes warning on deprecated argument from product get_dimentions() method

---

includes/class-wcpdf-main.php

This PR introduces the `wpo_wcpdf_remove_order_personal_data_meta` filter hook, which allows you to override the default behavior of the document data removal, enabled by default.
You can use the filter hook to disable the documents' data removal, this way:
```php
add_filter( 'wpo_wcpdf_remove_order_personal_data', '__return_false' );
```
Closes: #456

Add new filter to allow user to disable the documents' data removal

---

includes/documents/abstract-wcpdf-order-document.php
woocommerce-pdf-invoices-packingslips.php

I was thinking on this over the weekend, if for some reason we forgot the debug enabled and push changes to the branch and nobody notice could be problematic for customers, so I think we should use a filter instead.

Replaces yearly debug enable property with filter

---

includes/class-wcpdf-pdf-maker.php
includes/documents/abstract-wcpdf-order-document.php
includes/documents/class-wcpdf-bulk-document.php
includes/wcpdf-functions.php

A customer required a dynamic paper height for Packing Slip using mPDF extension. Currently the PDF maker class doesn't have a way to identify the current document. This PR addresses this by passing the document object in the construct arguments and also to render filters.

Adds a document object arg to PDF maker class

---

includes/class-wcpdf-admin.php

I notice in a customer store strange order comments, and after investigating I found that when the order is saved, for example when changing the order status to completed, our plugin function `save_invoice_number_date()` is triggered. Because the document data is empty, and we don't do a check on that, the order comments were registered anyway here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/5048ca51bcfed8db1eba4e0f5ae72ecdbf01bfa6/includes/class-wcpdf-admin.php#L692
These are the wrongly registered comments:
The PDF in this case was generated in the completed email trigger.

Bail is document data is empty when saving order

---

includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php

FIx: Replace the use of the deprecated `wcs_renewal_order_meta` hook

---

includes/class-wcpdf-install.php
includes/class-wcpdf-main.php

I tried several times to reproduce this issue by installing version 3.5.4 and upgrading to the latest version 3.5.5 multiple times, but I did not encounter the reported problem.
Upon reviewing the codes, I found out that the upgrade method always copies fonts in any situation. So, this issue is strange because everything seems fine!
I read support tickets related to this problem in both HelpScout and wordpress.org after the latest release, and I saw a few tickets related to the fonts issue, but none of them specifically referred to any problems associated with the "upgrade" process.
Also, about another individual's comment in the main topic (https://wordpress.org/support/topic/had-to-manually-reinstall-plugin-fonts/), I'm not sure whether he had this issue after the upgrade or not! …

Fix: font deletion bug after plugin upgrade

---

includes/documents/abstract-wcpdf-order-document-methods.php

closes #558
Code snippet for testing:
```php
add_action( 'wpo_wcpdf_before_document', function( $document_type, $order ) {
add_filter( 'gettext', 'wpo_translate_shipping_note', 10, 3 );
}, 10, 2 );
add_action( 'wpo_wcpdf_after_document', function( $document_type, $order ) {
remove_filter( 'gettext', 'wpo_translate_shipping_note', 10, 3 );
}, 10, 2 );
function wpo_translate_shipping_note( $translation, $text, $domain ) {
$translation = str_ireplace( 'Commande entièrement remboursée', 'Pedido reembolsado totalmente', $translation );
return $translation;
}
```

Fix: allows the translation for the Shipping Notes strings

---

includes/documents/abstract-wcpdf-order-document-methods.php

closes #570
New filter to impede strip HTML tags from the Shipping Notes: `wpo_wcpdf_shipping_notes_strip_all_tags`

New: filter hook to impeding Shipping Notes strip HTML tags

---

includes/class-wcpdf-main.php
includes/settings/class-wcpdf-settings-debug.php

closes #577
This will make the option to generate a new random string for the temporary directory always visible:

Fix: bug when the temporary directory is not secured but the option exists in the database

---

includes/class-wcpdf-admin.php

closes #595 
If you require multiple dummy orders to be created, you can use this plugin:
https://wordpress.org/plugins/generate-random-orders-for-woocommerce/.
If used, an update on their status using bulk action is recommended.

Fix: add missing "Invoice Number" column to orders export of WooCommerce analytics

---

.github/workflows/lint.yml
includes/views/dompdf-status.php
readme.txt
woocommerce-pdf-invoices-packingslips.php

New: bump min required PHP version to 7.2

---

includes/settings/class-wcpdf-settings-ubl.php

Since these settings are in the same context, that is the WP dashboard, it does not have much sense to open a new tab for these specific links.

Remove `target="_blank"` from UBL settings links

---

includes/class-wcpdf-admin.php

Fix: error when calling order ID on null under `output_number_date_edit_fields` method

---

includes/wcpdf-functions.php

Fix: potential fatal error if document is `false` in order list action buttons

---

includes/class-wcpdf-endpoint.php
includes/class-wcpdf-frontend.php
includes/class-wcpdf-install.php
includes/class-wcpdf-settings.php
includes/documents/abstract-wcpdf-order-document.php
includes/wcpdf-functions.php

closes #620 
This PR fixes an issue when trying to output the document as HTML using pretty links.
This PR also improves the pretty link to include the output at the end:
- PDF render: `.../wcpdf/invoice/575/e28f82db34/pdf`
- HTML render: `.../wcpdf/invoice/575/e28f82db34/html`
- UBL download: `.../wcpdf/invoice/575/e28f82db34/ubl`
- The default link still uses: `&output=html`

Fix: bug with HTML output using pretty links. Improved endpoint. 

---

includes/documents/abstract-wcpdf-order-document.php

closes #634
Fixes bug introduced on this PR https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/632

Fix: bug on document variable name on `output_ubl` method

---

includes/documents/abstract-wcpdf-order-document.php
includes/documents/class-wcpdf-invoice.php

Fix: bug on historical settings not being deleted when using most current settings

---

includes/views/advanced-status.php

`Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /wp-includes/kses.php on line 1744
`

Fix PHP 8.1 preg_replace warning

---

includes/documents/abstract-wcpdf-order-document-methods.php
includes/documents/abstract-wcpdf-order-document.php
templates/Simple/invoice.php

#659
This PR improves the templates display functions:
New functions:
```php
$this->number( $document_type );
$this->date( $document_type );
$this->number_title();
$this->date_title();
$this->due_date_title();
``` 
Deprecated functions:
`get_invoice_number`
`invoice_number`
`get_invoice_date`
`invoice_date`
Changed functions:
`get_number`: now includes `$formatted` `bool` arg
`get_date`: now includes `$formatted` `bool` arg

Tweak: improves the templates number/date functions

---

includes/class-wcpdf-main.php
includes/class-wcpdf-settings.php
includes/class-wcpdf-updraft-semaphore.php
includes/documents/class-wcpdf-invoice.php
includes/settings/class-wcpdf-settings-debug.php

closes #619 
This PR attempts to fix the race condition issue spotted using Stripe plugin.
It changes the lock time to `60` seconds, to avoid expiring before the code being finished, and now also adds a lock to the email attachment function as well, which is the primary way of getting duplicated numbers.

Fix: Invoice number race condition

---

includes/documents/class-wcpdf-invoice.php

Tweak: re-adds the legacy hook `woocommerce_invoice_number` for backwards compatibility

---

includes/documents/abstract-wcpdf-order-document.php
includes/documents/class-wcpdf-invoice.php
includes/documents/class-wcpdf-packing-slip.php

This new parameter is required to pass the `output` key, which can be `ubl`.

Tweak: includes `$args` in filter hook `wpo_wcpdf_filename` parameters

---

includes/class-wcpdf-main.php

When the access type is set to "Full," using bulk actions to generate an invoice for a single order results in a permission error. Still, it's working correctly if several orders have been chosen.

Fix a bug in "Full" document access

---

includes/documents/abstract-wcpdf-order-document-methods.php

If there is no paid date for an order, the `get_date_paid()` returns null, and it can lead to this error:
`
Fatal error: Call to a member function getTimestamp() on null
C:\laragon\www\mohamad\wp-content\plugins\woocommerce-pdf-invoices-packing-slips\includes\documents\abstract-wcpdf-order-document-methods.php (478)
`

Fix a bug in `get_payment_date()`

---

languages/strings.php

Currently, we are using the "Payment Date:" string within the Receipt document in both Professional and Premium Templates extensions, but it has not yet been declared within our free main plugin.

Declare new "Payment Date:" string

---

languages/strings.php

Currently, we are using the "Payment Date:" string within the Receipt document, but it has not yet been declared.
Related with #683.

Declare new "Payment Date:" string (II)

---

includes/class-wcpdf-settings.php
includes/settings/class-wcpdf-settings-upgrade.php
includes/views/advanced-tools.php
includes/views/settings-page.php

closes #686
This PR hides the Upgrade tab on valid bundle (Pro + Templates valid licenses), and implements a new caching system for the licenses data. This new caching system will replace the current Pro license caching.
New tool to clear the licenses cache:
Includes also a new notice in the Upgrade tab about the caching:

New: hides the Upgrade tab on bundle. New extensions license cache system

---

includes/class-wcpdf-updraft-semaphore.php

When using the renumber tool, I got this error:
```
WC_Logger::log was called incorrectly. <code>WC_Logger::log</code> was called with an invalid level "debug ". Backtrace: do_action('wp_ajax_wpo_wcpdf_danger_zone_tools'), WP_Hook->do_action, WP_Hook->apply_filters, WPO\WC\PDF_Invoices\Settings\Settings_Debug->ajax_process_danger_zone_tools, WPO\WC\PDF_Invoices\Settings\Settings_Debug->renumber_or_delete_document, WPO\WC\PDF_Invoices\Documents\Invoice->init_number, WPO\WC\PDF_Invoices\Updraft_Semaphore_3_0->lock, WPO\WC\PDF_Invoices\Updraft_Semaphore_3_0->ensure_database_initialised, WPO\WC\PDF_Invoices\Updraft_Semaphore_3_0->log, WC_Logger->log, wc_doing_it_wrong. This message was added in version 3.0.
````

Fix the level parameter sent to the log() method

---

includes/views/settings-page.php

#677
Hides the extensions banner temporarily until we get a better/updated one.

Tweak: hides the extensions banner temporarily

---

includes/class-wcpdf-admin.php
includes/class-wcpdf-install.php
includes/documents/abstract-wcpdf-order-document.php
includes/documents/class-wcpdf-bulk-document.php
includes/documents/class-wcpdf-invoice.php
includes/documents/class-wcpdf-packing-slip.php
includes/settings/class-wcpdf-settings-debug.php
woocommerce-pdf-invoices-packingslips.php

Fix: renumbering documents not working

---

includes/wcpdf-functions.php

Based on @brualio suggestion via Slack DM to avoid having a fatal error when calling this function by passing a `$document` value has `false` on `wcpdf_get_document_file`. This way we could determine how the function should handle the errors.

New: function `wcpdf_error_handling`

---

includes/class-wcpdf-main.php

This PR switches the condition for the "Disable for free orders" option to the document settings instead of the historical setting (stored within the order data at the moment of its creation).
Closes: #719

Check document settings for the "Disable for free orders" option

---

includes/class-wcpdf-admin.php

Closes #714 
The default nonce name `_wpnonce` was causing the conflict, so it was changed to `_wpdismissnonce`.

Changed default nonce name for wizard dismissal

---

includes/documents/abstract-wcpdf-order-document-methods.php

close #716 
The Getters method exists in version `3.0.0`:
https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/class-wc-order-item-coupon.php
https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/class-wc-order-item-fee.php
https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/class-wc-order-item-product.php
https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/class-wc-order-item-shipping.php
https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/class-wc-order-item-tax.php

Update `get_tax_rate` method to use Woo getters

---

includes/class-wcpdf-admin.php
includes/documents/abstract-wcpdf-order-document-methods.php
readme.txt
woocommerce-pdf-invoices-packingslips.php

Following the same bump for the next Pro extension release, I think we should also do the same here.

New: bumps WooCommerce min version to 3.3

---

includes/documents/abstract-wcpdf-order-document.php

Fix: `is_allowed()` method not considering parent order status on Credit Note document

---

includes/settings/class-wcpdf-settings-debug.php

With this filter you can alter the date type, for example to `date_paid`:
```php
add_filter( 'wpo_wcpdf_process_danger_zone_tools_date_type', function( $date_type, $request ) {
return 'date_paid';
}, 10, 2 );
```
Following this forum message: https://wordpress.org/support/topic/renumber-existing-documents-not-working/#post-17445160

New: filter `wpo_wcpdf_process_danger_zone_tools_date_type`

---

includes/class-wcpdf-admin.php

When HPOS is enabled the filter `woocommerce_order_table_search_query_meta_keys` needs to be executed.
The other filter is only relevant when CPT orders are in use.
References:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableSearchQuery.php#L241-L254
https://stackoverflow.com/a/77752011

HPOS: Add new filter to include invoice number in search queries

---

includes/wcpdf-functions.php

Fix: bug with type hint in `wpo_wcpdf_parse_document_date_for_wp_query()`

---

includes/settings/class-wcpdf-settings-debug.php

This PR addresses an issue spotted on the Professional extension, which lead to issues in the Bulk Export when using the Document date.
The `meta_query` key used by `wc_get_orders`, and built by our function `wpo_wcpdf_parse_document_date_for_wp_query`, is only available on HPOS.

Fix: document date parse function being called on non HPOS stores

---

includes/wcpdf-functions.php

The `<p>` tag is necessary to display order notes correctly, and it's safe to add this to the default allowed tags.

Add  `<p>` tag to allowed tag of the `wpo_wcpdf_sanitize_html_content()` method

---

includes/settings/class-wcpdf-settings-upgrade.php

Fix: the function `get_extensions_license_data` returning empty if no cached data found

---

includes/class-wcpdf-admin.php

Beside the slug include the key `customer_invoice`, this email just sends the order details. I think we should revert this.

Fix: reverts the `customer_invoice` email title to the original Woo title

---

includes/documents/class-wcpdf-document-number.php

Fix: Number formatting `[order_number]` placeholder not using parent order number on Credit Notes

---

includes/settings/class-wcpdf-settings-callbacks.php

closes #815
The current variable was returning an array when adding a new language instead of an empty string:

Fix: settings language tab issue when adding new language

---

includes/documents/abstract-wcpdf-order-document-methods.php

close #830 
By the fix provided in this PR, the VAT label has been translated:

Make totals labels translatable

---

includes/class-wcpdf-admin.php

close #844
Sample usage:
Add a note field to the Proforma document:
```php
function wpo_add_notes_to_proforma( $data, $document ): array {
$data['notes'] = array(
'label' => __( 'Notes', 'woocommerce-pdf-invoices-packing-slips' ),
);
return $data;
}
add_filter( 'wpo_wcpdf_metabox_data_fields', 'wpo_add_notes_to_proforma', 10, 2 );
```
Result:

Apply a filter to modify PDF document data fields

---

includes/class-wcpdf-admin.php

Adjusted the priority from `999` to `200` to ensure compatibility with Admin Columns plugin: https://www.admincolumns.com/

Tweak: lower hook priority for Invoice columns in WC orders list

---

woocommerce-pdf-invoices-packingslips.php

closes #870
- Translations must be loaded before the classes to ensure that all translatable strings are available when needed.
- The classes should be initialized with a lower priority compared to the Pro extension to prevent potential conflicts or issues.

Fix: load plugin translations later on `init`

---

includes/class-wcpdf-main.php

Prevent unauthenticated users to enable debug and error reporting.

Check current user role in the `enable_debug` function

---

includes/documents/abstract-wcpdf-order-document.php

Deprecated hooks have been added to the `get_due_date()` function to prevent errors from occurring due to changes in the number of arguments sent to hooks.

Update due date hooks

---

includes/documents/abstract-wcpdf-order-document.php
includes/documents/class-wcpdf-invoice.php
includes/documents/class-wcpdf-packing-slip.php

Fix: adds missing deprecated filters to document title methods

---

templates/Simple/style.css

closes #905
This PR removes the space between the items table and the totals:

New: removes space between items table and totals

---

includes/Assets.php

closes #915
Although I couldn't replicate the issue, this improvement has the potential to resolve it.

Fix: jQuery `tipTip` function not available

---

includes/Settings.php
includes/Settings/SettingsDocuments.php
includes/Settings/SettingsUbl.php

This PR renames the main plugin settings tab from 'UBL' to 'Taxes' for improved clarity and adds a descriptive text to enhance the user experience on that page.

Tweak: move UBL support out of beta

---

wpo-ips-functions.php

closes #974
This function uses the `translate()` function to retrieve translations for runtime-determined strings, with a fallback to the original string if no translation exists. It ensures compatibility with existing `.po` translations while safely handling cases where the `translate()` function is unavailable.

New: add utility function for dynamic string translation

---

ubl/Documents/Document.php
ubl/Settings/TaxesSettings.php

closes #986
This PR removes the default "standard" selector for the UBL Tax Reason. In most cases, specifying a tax reason is unnecessary, and having a universal default for all taxes is generally impractical.

Tweak: removes standard default selector for UBL Tax Reason

---

templates/Simple/style.css

closes #976 
**IMPORTANT NOTE - Do the same changes in templates plugin for all templates.**
Done - https://github.com/wpovernight/woocommerce-pdf-ips-templates/issues/364

Logo height setting can break document layout

---

ubl/Handlers/Common/TaxTotalHandler.php

Fix: UBL Tax reason output `none` to file

---

ubl/Documents/UblDocument.php

closes #1006
This enhancement is necessary to accommodate country-specific format requirements.

New: add support for multiple handlers under a single root in `UblDocument::get_data()`

---

wpo-ips-functions.php

Tweak: Replace `translate()` with `gettext` filters in dynamic translation function

---

includes/Documents/OrderDocument.php

Fix: `OrderDocument::get_language_attributes()` return value must be of type string, null returned

---

templates/Simple/style.css

Fix: Product bundle border bottom in PDF template styles

---

includes/Documents/OrderDocumentMethods.php

close #1063 
Document note after this PR:

Apply `wpautop()` to document notes

---

includes/Documents/BulkDocument.php

Clean up special characters in `get_html()` of Bulk Document

---

views/advanced-numbers.php

Fix: Missing translation function for string on Advanced Numbers page

---

wpo-ips-functions.php

Fix: Restore `translate()` fallback in `wpo_wcpdf_dynamic_translate()` function

---

includes/Makers/PDFMaker.php
includes/Settings/SettingsDebug.php

closes #1116
Added a new method to the `PDFMaker` class to enable Dompdf's additional debug options when the plugin's debug setting is active. This provides more detailed output in the `log.htm` file to help troubleshoot rendering issues. Options are also filterable via `wpo_wcpdf_dompdf_additional_debug_options`.

New: Adds Dompdf log file reference and enable additional debug output when debug mode is active

---

includes/Tables/NumberStoreListTable.php

closes #1130
Invoices were incorrectly marked as "gapped" in **Advanced > Numbers** when other document types reused the invoice numbering system.

Fix: "Gapped" invoices shown when other documents used the invoice numbering

---

includes/Documents/OrderDocumentMethods.php

Fix: Deprecation warning for `null` value passed to `substr()` when extracting thumbnail URL

---

includes/Compatibility/FileSystem.php
includes/Install.php
includes/Settings/SettingsDebug.php

closes #1165
This PR also improves the reliability of the WP_Filesystem initialization process.

Tweak: Set PHP file functions as default method in Filesystem class due to WP_Filesystem instability

---

includes/Semaphore.php

Fix: Wrong condition in `Semaphore::init_cleanup()` preventing cleanup run

---

readme.txt
ubl/Settings/TaxesSettings.php
woocommerce-pdf-invoices-packingslips.php

Fix: Fatal error when calling `WC_Tax::get_tax_rate_classes()` on older Woo versions

---

includes/Admin.php
includes/Settings/SettingsDebug.php

close #1274
This PR introduces a new setting under the Advanced settings to allow choosing the default invoice number value for the "PDF document data" editing form.

New setting to allow choosing default manual invoice number
