wpovernight/woocommerce-pdf-invoices-packing-slips

woocommerce-pdf-invoices-packingslips.php
Applies operations on mofile only on filename and not on path (folders)
Fixes #76
=> Textdomain fallback file operations fix

includes/documents/abstract-wcpdf-order-document.php
=> Check if document is enabled before allowing it to generate

includes/documents/class-wcpdf-invoice.php, includes/documents/class-wcpdf-packing-slip.php, templates/Simple/invoice.php, templates/Simple/packing-slip.php
=> More billing/shipping address visibility options

includes/class-wcpdf-documents.php
=> only apply wpo_wcpdf_document_classes filter once

includes/class-wcpdf-admin.php
Fixes issue #103 , removing a blank space that was present in the code.
Opened a new branch based off ea382b9 (tag: v2.7.0) as per previous pull request of #107.
Thanks Ewout for the patience!
=> Remove blank space in PDF actions buttons alignment (#103)

includes/compatibility/class-wc-order-compatibility.php
=> PHP8 compatibility

assets/css/order-styles.css, assets/js/order-script.js, includes/class-wcpdf-admin.php, includes/documents/abstract-wcpdf-order-document.php, woocommerce-pdf-invoices-packingslips.php
=> Save invoice number and date with regenerate document #102

assets/js/order-script.js, includes/class-wcpdf-admin.php
=> Create universal document data functions for meta box

includes/class-wcpdf-setup-wizard.php
=> Set current screen on Wizard

includes/class-wcpdf-admin.php, includes/documents/abstract-wcpdf-order-document-methods.php, includes/wcpdf-functions.php
=> New date formatting function wcpdf_date_format()

includes/class-wcpdf-admin.php
closes #140
Tested and working!
=> Allow set an Invoice number and date prior to generate the PDF

templates/Simple/invoice.php, templates/Simple/style.css
=> Fix for the Simple template total alignment

includes/class-wcpdf-install.php
On line 175, "update_option" was changed to "add_option".
closes #150
=> Only set defaults when option not set yet

assets/js/admin-script.js, assets/js/order-script.js, assets/js/setup-wizard.js, includes/class-wcpdf-settings-callbacks.php, includes/views/wcpdf-extensions.php
=> Fix jQuery Migrate warnings

includes/views/dompdf-status.php
- Adds PHP version to System Configuration
- Code cleaning
closes #168
=> Adds PHP version to status System Configuration. Code cleaning.

assets/js/order-script.js, includes/class-wcpdf-main.php, includes/class-wcpdf-settings-debug.php, includes/documents/class-wcpdf-invoice.php
=> Log Invoice generate info to order notes with setting enabled.

includes/documents/abstract-wcpdf-order-document.php, templates/Simple/invoice.php, templates/Simple/packing-slip.php
From here: https://github.com/wpovernight/woocommerce-pdf-ips-templates/pull/54#issuecomment-824620969
=> New footer hooks

assets/css/order-styles.css, assets/js/order-script.js, includes/class-wcpdf-admin.php, includes/class-wcpdf-assets.php
=> Adds a Save and Cancel buttons to the Document Data metabox

includes/class-wcpdf-admin.php, includes/class-wcpdf-main.php, includes/class-wcpdf-settings-debug.php, includes/class-wcpdf-settings-general.php, includes/class-wcpdf-settings.php, includes/documents/abstract-wcpdf-order-document.php, includes/documents/class-wcpdf-invoice.php, includes/views/attachment-settings-hint.php, includes/views/dompdf-status.php, includes/views/wcpdf-extensions.php, woocommerce-pdf-invoices-packingslips.php
=> Improve internationalization of the plugin (i18n)

templates/Simple/html-document-wrapper.php
=> New filter 'wpo_wcpdf_body_class' to allow override the body class

includes/documents/abstract-wcpdf-order-document.php
=> New filter 'wpo_wcpdf_html_content' for the HTML content.

assets/js/my-account-link.js, includes/class-wcpdf-frontend.php
=> Open PDF on My Account page in a new browser tab/window

includes/documents/abstract-wcpdf-order-document.php, includes/documents/class-wcpdf-invoice.php, includes/documents/class-wcpdf-packing-slip.php, templates/Simple/invoice.php
https://github.com/wpovernight/woocommerce-pdf-ips-pro/issues/22
=> Adds new methods to get the document number and date titles

templates/Simple/invoice.php, templates/Simple/packing-slip.php
=> Adds new 'item-' prefix to PDF order items class

includes/class-wcpdf-main.php
=> New filter to disable order ids reverse in bulk actions

assets/js/my-account-link.js
=> fix-myaccount-console-errors

includes/documents/abstract-wcpdf-order-document.php
closes https://github.com/wpovernight/woocommerce-pdf-ips-pro/issues/98
=> Returns the setting first key if 'default' is empty

includes/class-wcpdf-frontend.php
=> Undefined variable $order when using [wcpdf_download_invoice] shortcode in PHP 8

includes/class-wcpdf-main.php
=> Fixes bug on trying to add notes to refund orders

.github/workflows/minify.yml
=> Updates the minify action using just push

templates/Simple/packing-slip.php
=> Phone not displaying in Packing Slip

includes/class-wcpdf-admin.php, includes/class-wcpdf-frontend.php
Affected areas:
- Shortcode `[wcpdf_download_invoice]`
- My account invoice button/link
- Backend buttons in order details page
- Action buttons in order list
=> use add_query_arg for URL creation, escape output

includes/class-wcpdf-admin.php, includes/class-wcpdf-main.php, includes/class-wcpdf-settings-callbacks.php, includes/class-wcpdf-settings-debug.php, includes/class-wcpdf-settings-documents.php, includes/class-wcpdf-settings-general.php, includes/class-wcpdf-settings.php, includes/documents/abstract-wcpdf-order-document.php, includes/views/attachment-settings-hint.php, includes/views/dompdf-status.php, includes/views/wcpdf-extensions.php, includes/views/wcpdf-settings-page.php, includes/wcpdf-functions.php, woocommerce-pdf-invoices-packingslips.php
This PR focuses primarily on escaping / sanitizing settings windows and a few other backend contexts.
Please review code (checking to see if any strings were missing) as well as output (verifying that the changes made still result in the correct output).
=> Backend cleanup

includes/class-wcpdf-settings.php
closes #243
Tested :heavy_check_mark:
=> Adds new filter and fallback for the default settings tab

includes/class-wcpdf-settings-callbacks.php, includes/class-wcpdf-settings-general.php, includes/documents/class-wcpdf-invoice.php
closes #253
* General tab :heavy_check_mark: 
* Documents > Invoice tab :heavy_check_mark:
=> Prevents unwanted queries when settings API are called outside the usual scopes

includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
=> Improves meta deletion for every enabled document in WCS renewal order

includes/class-wcpdf-settings.php
=> Adds a feedback notice on settings save

includes/class-wcpdf-main.php, includes/class-wcpdf-settings-callbacks.php, includes/class-wcpdf-settings-debug.php
closes #295
* Manual trigger from status page :heavy_check_mark: 
* Hook forcing attaching to a different hook `admin_init` :heavy_check_mark:
=> Improves temporary files cleanup. Adds dompdf dir to cleanup.

includes/documents/abstract-wcpdf-order-document.php, includes/documents/class-wcpdf-invoice.php
=> Don't store documents non historical settings in order meta

includes/documents/abstract-wcpdf-order-document-methods.php
=> wrapped wc_display_item_meta args in apply_filters

includes/class-wcpdf-main.php
=> Fix syntax in the path dynamic filter hook

includes/class-wcpdf-settings-debug.php
This PR adds a new button in the Status tab: **Run the Setup Wizard**:
Closes: #338
=> Add a button in the Status tab to relaunch the Setup Wizard

includes/class-wcpdf-settings.php, includes/documents/abstract-wcpdf-order-document.php
closes #350
Tested and working :heavy_check_mark:
=> Adds filter to disable historical settings on the Preview

includes/wcpdf-functions.php
=> Content length in response headers

templates/Simple/invoice.php, templates/Simple/packing-slip.php
Following yordan's note here [https://wpovernight.slack.com/archives/C0121KYKGN6/p1650392330309029]
Checked for payment method before displaying the payment label on the invoices.
=> added payment check for the simple template

includes/documents/abstract-wcpdf-order-document.php, includes/documents/class-wcpdf-bulk-document.php
=> Add `$this` as extra argument to `wpo_wcpdf_html_filters` & `wpo_wcpdf_pdf_filters`

includes/class-wcpdf-admin.php, includes/class-wcpdf-main.php, includes/documents/abstract-wcpdf-order-document.php, woocommerce-pdf-invoices-packingslips.php
=> Add filter hooks to override ability to edit document data

includes/class-wcpdf-frontend.php
=> Check if the invoice is allowed before the shortcode output

includes/views/wcpdf-settings-page.php
=> Fix: Use escaping function

templates/Simple/invoice.php, templates/Simple/packing-slip.php
=> Add action hooks before and after the shop logo

includes/class-wcpdf-main.php
closes #398
Tested :heavy_check_mark:
=> Replaces WP_Filesystem with PHP functions to delete temporary files

includes/class-wcpdf-main.php
closes #400
Tested :heavy_check_mark:
=> Adds a fallback function to list files if for some reason the WP function isn't available

includes/class-wcpdf-frontend.php, includes/class-wcpdf-main.php
closes #402 
Waiting customer feedback! https://secure.helpscout.net/conversation/2016246216/40280
=> Adds a specific query string for the shortcode

includes/class-wcpdf-admin.php, includes/documents/abstract-wcpdf-order-document.php, includes/documents/class-wcpdf-invoice.php
=> Improved document settings functions to unify and simplify settings init

README.md, includes/class-wcpdf-admin.php, includes/class-wcpdf-main.php, includes/class-wcpdf-setup-wizard.php, includes/views/wcpdf-extensions.php, includes/views/wcpdf-settings-page.php, languages/woocommerce-pdf-invoices-packing-slips.pot, license.txt, readme.txt, templates/Simple/template-functions.php, woocommerce-pdf-invoices-packingslips.php
=> Renames the plugin

includes/class-wcpdf-endpoint.php, includes/class-wcpdf-main.php, includes/class-wcpdf-settings.php
=> Filter to allow customers to access your PDF with a unique key.

includes/class-wcpdf-admin.php
=> Allow manually resending new order email

includes/class-wcpdf-main.php
=> Issue 418 avoid warning on automatic cleanup cron job

includes/class-wcpdf-main.php, includes/class-wcpdf-settings-debug.php, includes/documents/abstract-wcpdf-order-document.php
=> Maybe reinstall fonts before PDF output

includes/class-wcpdf-admin.php, includes/class-wcpdf-settings-callbacks.php, includes/class-wcpdf-settings-documents.php, includes/class-wcpdf-settings.php, includes/documents/abstract-wcpdf-order-document-methods.php, includes/documents/abstract-wcpdf-order-document.php, includes/legacy/class-wcpdf-legacy-settings.php, includes/views/dompdf-status.php, includes/views/setup-wizard/display-options.php, includes/views/wcpdf-settings-page.php, includes/wcpdf-functions.php, templates/Simple/html-document-wrapper.php, templates/Simple/invoice.php, templates/Simple/packing-slip.php
=> Check if HTML is escaped properly before echoing

includes/documents/abstract-wcpdf-order-document.php
=> Check if the shop logo exists

includes/documents/abstract-wcpdf-order-document-methods.php
Closes #438 
Original PR: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/434
=> Refactor get_phone() function

includes/class-wcpdf-admin.php, includes/documents/abstract-wcpdf-order-document-methods.php, includes/documents/abstract-wcpdf-order-document.php, templates/Simple/invoice.php, templates/Simple/packing-slip.php
closes #428
Reverts documents functions/templates escaping done in #408
=> Reverts documents functions escape

includes/class-wcpdf-main.php
=> Check if the order is unsaved or doesn't exist before rendering the PDF document

includes/class-wcpdf-admin.php, includes/documents/abstract-wcpdf-order-document-methods.php, languages/strings.php
=> Restore the 'VAT' and 'Tax rate' strings

templates/Simple/style.css
=> Break long URLs in different lines if it reaches the available space

includes/class-wcpdf-settings-general.php, includes/views/attachment-settings-hint.php
=> Add nonce in hide link in administration section

includes/class-wcpdf-admin.php, includes/class-wcpdf-main.php, includes/views/wcpdf-extensions.php, includes/views/wcpdf-settings-page.php, woocommerce-pdf-invoices-packingslips.php
=> Fix: Add nonces to several admin unsecure requests

includes/class-wcpdf-settings.php, includes/class-wcpdf-setup-wizard.php, woocommerce-pdf-invoices-packingslips.php
=> New: filter to change role capabilities to access plugin settings

includes/wcpdf-functions.php, woocommerce-pdf-invoices-packingslips.php
=> New: adds notice when RTL is detected

includes/class-wcpdf-admin.php, includes/compatibility/class-wcpdf-order-util.php, woocommerce-pdf-invoices-packingslips.php
=> Fix: invoice number/date screen options bug with HPOS enabled

includes/wcpdf-functions.php, woocommerce-pdf-invoices-packingslips.php
=> fix fatal error on WC deactivation

includes/class-wcpdf-main.php
=> Tweak: adds user permission check on AJAX document printed

includes/class-wcpdf-main.php, includes/documents/abstract-wcpdf-order-document.php
=> Fix: disallow document creation for anonymized orders

includes/class-wcpdf-main.php, includes/documents/class-wcpdf-bulk-document.php
=> Fix: bug on trying to save bulk document setting on `document_can_be_manually_marked_printed()`

includes/class-wcpdf-settings.php, includes/documents/class-wcpdf-invoice.php
=> Fix: adds semaphore to Invoice number init to prevent concurrent number issues

includes/documents/class-wcpdf-invoice.php
=> Fix: bug in slug property not set when defining the lock name

includes/class-wcpdf-settings-upgrade.php
Currently the Upgrade tab only check license status from the built-in updater, this PR adds support for the legacy Sidekick as well.
=> Fix: adds support for legacy Sidekick activated licenses in Upgrade tab

includes/documents/class-wcpdf-invoice.php
=> Fix: log invoice number generation on setting

includes/class-wcpdf-main.php
closes #524
Waiting customer feedback :hourglass:
=> Fix: PHP error on log_document_creation_trigger_to_order_meta() function when trying to get order ID

includes/class-wcpdf-frontend.php
=> New: Add a frontend shortcode for packing slip

includes/class-wcpdf-settings.php, woocommerce-pdf-invoices-packingslips.php
=> Fix: PHP8.2 Creation of dynamic property deprecated warnings

templates/Simple/style.css
=> Fix: Revert breaking long characters

includes/class-wcpdf-main.php
=> Fix: bug when trying to delete temporary files when using mPDF extension

includes/wcpdf-functions.php
=> Fix: UTF-8 decode functions bug with `mb_convert_encoding`

includes/documents/abstract-wcpdf-order-document.php, includes/wcpdf-functions.php
=> Fix: string encoding issues in PDF

.distignore, .github/workflows/release-assets.yml
=> Adds action for release assets

includes/class-wcpdf-main.php, includes/settings/class-wcpdf-settings-debug.php
=> Fix: remove old temp dir when generating new one from status tool

woocommerce-pdf-invoices-packingslips.php
=> New: adds notice for the upcoming PHP 7.2 requirement

includes/class-wcpdf-frontend.php
=> Add new parameters to shortcode, and create a new shortcode

includes/compatibility/class-wcpdf-order-util.php
=> Fix undefined method 'is_admin_page' bug

includes/class-wcpdf-documents.php, includes/views/wcpdf-settings-page.php
=> Fix: PHP error on calling `get_title()` document method on bool

includes/class-wcpdf-main.php, includes/class-wcpdf-settings.php
=> Fix: output html URL query string not working

includes/class-wcpdf-frontend.php
closes #611
One user tested and it's working fine :heavy_check_mark:
=> Fix: my account PDF link conflict with Jetpack analytics module

includes/class-wcpdf-admin.php
=> Fix: bug when displaying the Invoice number/date columns. Significant drop of performance.

includes/settings/class-wcpdf-settings-ubl.php
=> Fix: bug on UBL notice not hiding

includes/documents/abstract-wcpdf-order-document.php
=> Fix: bug on UBL preview that forces the invoice creation

includes/class-wcpdf-main.php
=> Fix empty argument bug for `display_due_date` method

includes/class-wcpdf-main.php
@alexmigf I was not sure about the comment. Let me know please If you have a better suggestion.
=> Fix: revert handling access keys

includes/documents/abstract-wcpdf-order-document.php
=> Fix: due date not displaying in preview

includes/documents/abstract-wcpdf-order-document-methods.php
Reported [here](https://secure.helpscout.net/conversation/2431715557/56212/#thread-7311379206).
=> Bug: Fix a bug in "get_payment_date()"

ubl/Documents/Document.php
=> Fix: fatal error in UBL document

includes/settings/class-wcpdf-settings-debug.php, includes/tables/class-wcpdf-number-store-list-table.php
=> Fix: potential SQL injection bug in Number Tools

includes/tables/class-wcpdf-number-store-list-table.php, includes/views/advanced-numbers.php
=> Fix: SQL injection bug in Advanced Numbers search

includes/class-wcpdf-main.php
=> Make translatable the due date output

includes/class-wcpdf-admin.php
=> Fix sorting orders by invoice number and date issue on the orders page

includes/tables/class-wcpdf-number-store-list-table.php, includes/views/advanced-numbers.php
=> Fix: number tool pagination

includes/documents/class-wcpdf-bulk-document.php
=> Fix: bulk document missing slug property

includes/class-wcpdf-assets.php
Fixes console error:
> Uncaught TypeError: "$(...).pointer" is not a function
=> Fix: JS error `$(...).pointer` is not a function

includes/documents/abstract-wcpdf-order-document-methods.php
=> Fix "get_tax_rate" issue when the tax class is "inherit"

includes/documents/class-wcpdf-invoice.php, includes/documents/class-wcpdf-packing-slip.php
=> Replace `date()` with `date_i18n()` to set the date for the PDF filename (bulk action export)

includes/settings/class-wcpdf-settings-debug.php
=> Add hooks to allow adding new tabs and their contents

includes/class-wcpdf-admin.php
close #745 
The issue only happens when the HPOS is disabled.
=> Fix: Incorrect sorting orders for some column

includes/wcpdf-functions.php
=> Fix: bug calling `is_allowed()` on `bool`

includes/documents/abstract-wcpdf-order-document-methods.php
=> Fix: filter called with a refund object in `get_billing_address()`

includes/class-wcpdf-admin.php
=> Fix: customer invoice email title under "Send order email" metabox

includes/documents/abstract-wcpdf-order-document-methods.php, includes/wcpdf-functions.php
=> Fix: bug created by the output of the function `wpo_wcpdf_sanitize_html_content()` being `null`

includes/documents/class-wcpdf-invoice.php
This setting is not being used anymore and could be removed.
=> Remove "Log invoice number generation" setting

includes/documents/abstract-wcpdf-order-document-methods.php, includes/wcpdf-functions.php
=> Remove unwanted tags from `wpo_wcpdf_sanitize_html_content()`

includes/settings/class-wcpdf-settings-callbacks.php, includes/wcpdf-functions.php, woocommerce-pdf-invoices-packingslips.php
=> New: adds filter hooks to `i18n_wrap` to extend languages to third parties

includes/settings/class-wcpdf-settings-callbacks.php
=> Fix `normalize_settings_args` bug

includes/class-wcpdf-main.php, includes/settings/class-wcpdf-settings-debug.php
=> Register a log for document deletion in the Order Notes

includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
=> Add row classes for "YITH WooCommerce Product Bundles"

templates/Simple/invoice.php, templates/Simple/packing-slip.php
=> Wrap address around P tag

includes/class-wcpdf-settings.php, includes/documents/abstract-wcpdf-order-document.php, includes/makers/class-pdf-maker.php, includes/settings/class-wcpdf-settings-debug.php, includes/views/advanced-status.php, includes/wcpdf-functions.php, woocommerce-pdf-invoices-packingslips.php
Adds a new setting under **Advanced > General**:
=> Tweak: improved header logo loading

includes/documents/abstract-wcpdf-order-document.php
=> Fix: `get_header_logo_id()` return type fatal error

includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
=> Fix: function `add_yith_product_bundles_classes()` errors

includes/class-wcpdf-updraft-semaphore.php, includes/settings/class-wcpdf-settings-debug.php, includes/views/advanced-tools.php, woocommerce-pdf-invoices-packingslips.php
=> New: automatic cleanup of unlocked Semaphore locks. Other improvements.

includes/wcpdf-functions.php
This is a helper function that can be used by extensions.
=> New: function to determine if checkout is using block

includes/Main.php
=> Deprecate `wpo_wcpdf_due_date_display` hook

woocommerce-pdf-invoices-packingslips.php
=> New: Add notice about dropping support for PHP versions below 7.4

includes/Install.php, includes/Main.php, views/advanced-status.php, woocommerce-pdf-invoices-packingslips.php, wpo-ips-functions.php
=> New: raised the minimum PHP version requirement to 7.4

includes/Documents/Invoice.php, includes/Settings/SettingsDocuments.php
These improvements are necessary to enable the addition of custom document settings format tabs:
=> Tweak: settings improvements

includes/Main.php
close #864 
This PR adds the user display name and ID to the order note for invoice creation and deletion:
=> Add user info to order note

includes/Settings/SettingsDebug.php
=> Replace `function_exists` with `extension_loaded`

woocommerce-pdf-invoices-packingslips.php
=> New: Displays a notice if the yearly reset action is not scheduled

includes/Documents/OrderDocument.php
=> Fix: Incorrect treatment of UBL format setting as historical

includes/Documents/PackingSlip.php
=> Apply `wpo_wcpdf_settings_fields_documents_{$this->type}_pdf` before checking the emptiness of the `$settings_fields`

includes/Documents/OrderDocument.php
=> Allow 0 days for due date

includes/Settings/SettingsUbl.php, ubl/Documents/Document.php, ubl/Handlers/Common/TaxTotalHandler.php, ubl/Handlers/Invoice/InvoiceLineHandler.php, ubl/Settings/TaxesSettings.php
=> New: Support for UBL Tax Category Reason

ubl/Handlers/Invoice/InvoiceLineHandler.php
=> New: Add `cac:Price` support to UBL

ubl/Settings/TaxesSettings.php
=> New: filters for UBL tax schemes, categories, and reasons

ubl/Settings/TaxesSettings.php
=> Fix: revert UBL Tax Categories to full UN/EDIFACT list

ubl/Documents/UblDocument.php, ubl/Handlers/Common/PaymentMeansHandler.php
=> New: enable Support for `cac:PaymentMeans` in UBL

ubl/Settings/TaxesSettings.php
=> Fix postcode and city defaults in UBL tax output

includes/Settings/SettingsDebug.php, wpo-ips-functions.php
New: translation logs setting
closes #977
=> Tweak: improves the dynamic translate function.

includes/Documents/OrderDocument.php, includes/Main.php, ubl/Documents/Document.php
=> New: use dynamic UBL tax settings instead of saving to order

includes/Documents/OrderDocumentMethods.php
=> Tweak: apply `wpo_wcpdf_dynamic_translate()` to dynamically translated strings

includes/Install.php, readme.txt, woocommerce-pdf-invoices-packingslips.php
=> Fix: migrate UBL Tax Scheme settings

ubl/Handlers/Invoice/InvoiceLineHandler.php
=> New: add `cbc:BaseQuantity` support to UBL structure

includes/Documents/OrderDocument.php, includes/Settings/SettingsUbl.php, ubl/Documents/Document.php, ubl/Handlers/Common/TaxTotalHandler.php, ubl/Handlers/Invoice/InvoiceLineHandler.php, ubl/Settings/TaxesSettings.php, wpo-ips-functions-ubl.php
=> Tweaks: enhance UBL Taxes default selector, 'None' Option, and Regeneration

includes/Settings.php
=> Fix setting categories not applied for disabled documents

wpo-ips-functions-ubl.php
=> Tweak: improves UBL get tax data from fallback function

ubl/Handlers/Common/TaxTotalHandler.php
=> Tweak: default Item Tax Handling in `TaxTotalHandler`

ubl/Documents/Document.php, ubl/Handlers/Common/TaxTotalHandler.php, wpo-ips-functions-ubl.php, wpo-ips-functions.php
=> New: validation for order tax exemption to apply UBL tax reason

ubl/Handlers/Common/AddressHandler.php
=> Tweak: replace UBL code to get the customer VAT number with new function

includes/Documents/Invoice.php, wpo-ips-functions-ubl.php
=> Tweak: update UBL format selector description

includes/Admin.php, includes/Documents/OrderDocument.php, includes/Documents/OrderDocumentMethods.php, includes/Documents/SequentialNumberStore.php, includes/Install.php, includes/Main.php, includes/Semaphore.php, includes/Settings.php, includes/Settings/SettingsCallbacks.php, includes/Settings/SettingsDebug.php, includes/Settings/SettingsDocuments.php, includes/Tables/NumberStoreListTable.php, ubl/Settings/TaxesSettings.php, views/settings-page.php, views/upgrade-table.php, wpo-ips-functions.php
=> Fix: Additional fixes after Plugin Check revalidation

ubl/Builders/SabreBuilder.php
=> Fix: Call to undefined function standardSerializer() on UBL

includes/Settings.php
=> Tweak: Ignore Plugin Check Warnings for `register_setting()`

wpo-ips-functions.php
=> Check if `is_enabled()` is callable for the document in `wcpdf_get_document_file()`

templates/Simple/style.css
=> Fix: PDF totals style issue

includes/Documents/OrderDocument.php
=> Use `wp_kses_post` instead of `wpo_wcpdf_sanitize_html_content` for footer & extras

readme.txt
closes #954
I've decided to remove the UBL extensions from this section since they're already mentioned inside the plugin. Additionally, the list could grow significantly over time, and it may not be necessary to include them here.
=> Tweak: Enhanced the readme file to list available free extensions

ubl/Documents/Document.php
=> New: Add order coupons data to UBL document

templates/Simple/invoice.php, templates/Simple/packing-slip.php
=> Tweak: Refactor PDF Simple template order details header for cleaner syntax

includes/Documents/Invoice.php, includes/Endpoint.php, includes/Install.php, includes/Main.php, includes/Settings/SettingsDebug.php, woocommerce-pdf-invoices-packingslips.php
=> Remove guest access type

includes/Documents/OrderDocumentMethods.php
=> New: Add plugin-specific filter hook for order item name

ubl/Documents/UblDocument.php, ubl/Handlers/Common/AddressHandler.php
=> Fix: duplicate `AccountingSupplierParty` and `AccountingCustomerParty` in UBL

includes/Settings/SettingsDebug.php
=> Fix :SQL interpolation issues flagged by WP Plugin Check

views/advanced-tools.php
=> Fix: Improve date field options in Danger Zone tools for clarity

includes/Main.php
=> New: Improve fonts check and reinstatement in temporary fonts directory

includes/Install.php, includes/Main.php, includes/Settings/SettingsDebug.php
=> New: Adds setting to toggle PDF translation reload for email attachments

includes/Semaphore.php, includes/Settings.php, includes/Settings/SettingsDebug.php, includes/Settings/SettingsUpgrade.php, includes/Tables/NumberStoreListTable.php, woocommerce-pdf-invoices-packingslips.php
=> Fix: Missing global call to AS functions in Semaphore class

includes/Documents.php, includes/Main.php, readme.txt, woocommerce-pdf-invoices-packingslips.php
=> Fix: Fatal error when `null` is passed to `in_array()` in `Documents.php`

includes/Documents/OrderDocument.php, includes/Semaphore.php, woocommerce-pdf-invoices-packingslips.php, wpo-ips-functions.php
=> Fix: Missing log function fallback when dependencies are not loaded

includes/Settings.php
=> Improves the settings capability filter: `wpo_wcpdf_settings_user_role_capabilities`

includes/Documents/SequentialNumberStore.php
=> New: Add index on `order_id` column to document number database tables

includes/Frontend.php
=> Tweak: Improve Invoice My Account link logic for custom status checks and code clarity

includes/Compatibility/FileSystem.php, readme.txt, woocommerce-pdf-invoices-packingslips.php
=> Fix: Type error when accessing debug settings in `FileSystem` constructor

woocommerce-pdf-invoices-packingslips.php
=> Add permission check to pre-release notice display

includes/Semaphore.php, ubl/Settings/TaxesSettings.php, wpo-ips-functions.php
=> Fix: WP Plugin Check validation issues

includes/Documents/OrderDocument.php, readme.txt, woocommerce-pdf-invoices-packingslips.php
=> Fix: Restore `wpo_wcpdf_shop_address` hook for compatibility

includes/Settings/SettingsGeneral.php, templates/Simple/invoice.php, templates/Simple/packing-slip.php
=> New: Display shop phone number below address in Simple template

ubl/Settings/TaxesSettings.php
=> Tweak: Update UBL tax filters to append values instead of overriding defaults

includes/Settings/SettingsCallbacks.php
=> Fix: Remove incorrect email validation from nested settings

includes/Main.php
=> Proposal email attachment not working if PRO is not installed

includes/Main.php
=> Fix argument mismatch in `add_document_link_to_email`

readme.txt, woocommerce-pdf-invoices-packingslips.php, wpo-ips-functions.php
=> Fix: PHP warnings when `allow_url_fopen` is disabled

includes/Admin.php
=> Mark as printed date format issues

includes/Admin.php, includes/Frontend.php, views/setup-wizard/attach-to.php, wpo-ips-functions.php
=> Deprecate `wcpdf_get_invoice()` and `wcpdf_get_packing_slip()`

.distignore, includes/Frontend.php
=> Update WC order api hook

includes/Semaphore.php, includes/Settings/SettingsDebug.php
=> New: Add advanced setting to configure document lock cleanup frequency

includes/Frontend.php
=> Open PDFs in a new browser tab/window on the "Thank you" page
